In [10]:
#loading the data
import numpy as np
import pandas as pd
df = pd.read_excel('embeddingsdata.xlsx')
df 

embed_0   embed_1   embed_2   embed_3   embed_4   embed_5   embed_6  \
0    0.009625 -0.029216  0.027109  0.023631 -0.004972  0.031757 -0.045125   
1   -0.007535 -0.039844  0.030167  0.031224  0.004742  0.028289 -0.068723   
2    0.022408 -0.030840  0.032328  0.046965  0.007798  0.025860 -0.065093   
3    0.019677 -0.034055  0.012662  0.070387 -0.011170  0.017842 -0.050945   
4    0.017678 -0.030323  0.012829  0.065267 -0.025161  0.011964 -0.050590   
..        ...       ...       ...       ...       ...       ...       ...   
895  0.019743 -0.071799  0.022546  0.049042 -0.005767 -0.016275 -0.037731   
896  0.000186 -0.027604  0.010623  0.038237 -0.026675  0.020215 -0.040816   
897  0.018066 -0.032152  0.039794  0.047608  0.003898  0.024092 -0.056508   
898 -0.003492 -0.022739  0.021777  0.044054 -0.005621  0.013863 -0.079196   
899  0.013689 -0.037855  0.039763  0.035750  0.004115  0.005637 -0.050556   

      embed_7   embed_8   embed_9  ...  embed_759  embed_760  embed_761  \
0    0.044483  0.019400 -0.017189  ...  -0.001972  -0.008154  -0.056139   
1    0.039153  0.019596 -0.027138  ...   0.008613  -0.006578  -0.034220   
2    0.035118  0.035359 -0.029205  ...   0.020413  -0.034288  -0.050649   
3    0.044878  0.034781 -0.025772  ...   0.002963  -0.018754  -0.053278   
4    0.042820  0.029161 -0.015004  ...   0.010192  -0.010147  -0.035857   
..        ...       ...       ...  ...        ...        ...        ...   
895  0.029718  0.009203 -0.030913  ...  -0.001192  -0.026138  -0.056447   
896  0.032210  0.041016 -0.014836  ...   0.015479  -0.003967  -0.037808   
897  0.020527  0.031972 -0.026038  ...   0.011308  -0.016882  -0.059904   
898  0.039150  0.004557 -0.015787  ...   0.004005  -0.007196  -0.041652   
899  0.024668  0.025077 -0.029114  ...  -0.000129  -0.003880  -0.048696   

     embed_762  embed_763  embed_764  embed_765  embed_766  embed_767  Label  
0     0.009890   0.042366   0.040134   0.009304  -0.016137  -0.009309      0  
1     0.027574   0.045456   0.027402   0.017837  -0.035009  -0.010062      0  
2     0.028408   0.040412   0.030261   0.003535  -0.034122  -0.017289      0  
3     0.033005   0.031635   0.022544  -0.011774  -0.011125  -0.017540      0  
4     0.021784   0.034621   0.017342  -0.009884  -0.010316  -0.029238      0  
..         ...        ...        ...        ...        ...        ...    ...  
895   0.015818   0.045241   0.012620  -0.004837  -0.014540  -0.046791      2  
896   0.021234   0.031012  -0.010890   0.003081  -0.015145  -0.045444      0  
897   0.009558   0.039976   0.029574   0.013737  -0.003724  -0.017324      2  
898   0.020945   0.047604   0.019767   0.005806  -0.019280  -0.016415      5  
899   0.015711   0.039773   0.036328   0.010483  -0.021304  -0.032017      2  

[900 rows x 769 columns]

In [34]:
df.shape #no. of rows and columns in dataframe

(900, 769)

In [11]:
df['Label'].value_counts() #labels

0     363
1     246
2     107
5      65
6      36
9      24
4      20
10     12
3      10
8      10
7       7
Name: Label, dtype: int64

In [36]:
vec1 = np.array(df.loc[df['Label'] == 0]) #label 0 all features
vec1

array([[ 0.0096247 , -0.02921622,  0.02710896, ..., -0.01613726,
        -0.00930873,  0.        ],
       [-0.00753471, -0.03984416,  0.03016686, ..., -0.03500902,
        -0.01006159,  0.        ],
       [ 0.02240768, -0.03083997,  0.03232754, ..., -0.03412208,
        -0.01728851,  0.        ],
       ...,
       [ 0.01482519, -0.00914256,  0.02792686, ..., -0.02829061,
        -0.00559001,  0.        ],
       [-0.02357223, -0.03397999,  0.02247032, ...,  0.00616814,
        -0.02199391,  0.        ],
       [ 0.00018632, -0.02760411,  0.01062275, ..., -0.01514505,
        -0.04544352,  0.        ]])

In [28]:
vec2 = np.array(df.loc[df['Label'] == 1]) #label 1 all features
vec2

array([[ 2.04901863e-02, -3.33875678e-02,  4.10061702e-02, ...,
        -1.57155562e-02, -1.19352322e-02,  1.00000000e+00],
       [ 1.64230391e-02, -2.84842066e-02,  2.41031721e-02, ...,
        -2.39965580e-02, -1.82513054e-02,  1.00000000e+00],
       [ 3.00259865e-03, -3.40480208e-02,  2.84978934e-02, ...,
        -5.07440371e-03, -6.55643968e-03,  1.00000000e+00],
       ...,
       [ 1.23425405e-02, -1.15433987e-02,  3.65812853e-02, ...,
        -1.43688852e-02,  6.94988936e-04,  1.00000000e+00],
       [-6.38291566e-03, -3.08088399e-02,  3.19434740e-02, ...,
        -3.35947461e-02, -3.01798596e-03,  1.00000000e+00],
       [ 2.02006358e-03, -2.22974550e-02,  2.71005053e-02, ...,
         1.03340195e-02,  3.60116013e-03,  1.00000000e+00]])

In [31]:
mean_vec1 = np.mean(vec1, axis = 0) # mean for all features of label 0
mean_vec1

array([ 6.93396530e-03, -2.92363779e-02,  2.71120351e-02,  4.24414948e-02,
       -2.27521681e-03,  1.40538988e-02, -5.98755591e-02,  3.79871104e-02,
        3.28349247e-02, -2.48905972e-02,  3.76273041e-02, -4.44744284e-02,
        7.80751580e-02, -2.10547694e-03,  7.06716521e-02,  1.08736439e-02,
       -8.57578171e-03, -1.27622606e-02,  2.78747200e-02,  3.52300280e-02,
        1.41228108e-02, -4.31123486e-02, -3.50587808e-02,  1.63326926e-02,
       -4.03043819e-02,  2.43452528e-02,  8.07588033e-03, -2.39142361e-02,
       -1.74494194e-03,  3.03599488e-02,  5.20313514e-02, -5.20257869e-03,
       -1.19760621e-02,  5.45701038e-02, -4.18126885e-02,  2.56344932e-02,
       -3.57541222e-02, -6.19825985e-02, -3.88748499e-02,  1.19321084e-02,
        3.88917425e-03, -5.16110905e-02, -2.88013025e-02,  4.30589334e-02,
       -4.93740651e-02, -1.79521214e-02,  1.51590659e-02,  5.52739135e-02,
       -2.48371628e-02, -5.71472348e-02, -6.01828730e-02, -6.41265983e-02,
       -3.87850897e-02, -

In [37]:
mean_vec2 = np.mean(vec2,axis = 0) # mean for all features of label 1
mean_vec2

array([ 1.29317709e-02, -2.27106250e-02,  2.28574689e-02,  4.73383133e-02,
        7.43937132e-03,  1.59704238e-02, -5.96576000e-02,  4.14684116e-02,
        4.07638012e-02, -2.51692726e-02,  4.10164313e-02, -4.83275571e-02,
        7.17667071e-02, -2.02803838e-03,  6.89606468e-02,  6.86682520e-03,
       -4.82567751e-03, -2.20484806e-02,  2.87786109e-02,  4.01323101e-02,
        2.03454086e-02, -4.40025186e-02, -3.69915319e-02,  5.16141269e-03,
       -5.06904720e-02,  2.44396748e-02,  8.79747100e-03, -9.76339124e-03,
       -8.35384245e-03,  2.12778385e-02,  5.08130832e-02, -8.48950256e-03,
       -1.69995073e-02,  6.36571457e-02, -4.32606133e-02,  3.28738543e-02,
       -3.94713554e-02, -5.32995004e-02, -4.19309478e-02,  1.88866282e-02,
        2.68575049e-03, -5.71108354e-02, -3.09271170e-02,  4.66982710e-02,
       -4.06886292e-02, -1.30057865e-02,  1.41545241e-02,  5.75632675e-02,
       -1.76112684e-02, -5.90475477e-02, -6.60659808e-02, -6.80897755e-02,
       -4.10884902e-02, -

In [38]:
spread_vec1 = np.std(vec1,axis = 0) # standard deviation for all features of label 0
spread_vec1

array([0.01293223, 0.01390183, 0.0121483 , 0.01198753, 0.01227932,
       0.01115059, 0.01007727, 0.0099809 , 0.01148856, 0.009348  ,
       0.01108594, 0.01135964, 0.0106429 , 0.01045705, 0.0106025 ,
       0.01198376, 0.01016966, 0.0116819 , 0.01161697, 0.01025452,
       0.01158547, 0.01204993, 0.01263933, 0.01292106, 0.01311   ,
       0.01119263, 0.01130136, 0.0155473 , 0.01015887, 0.01194398,
       0.01200369, 0.0111692 , 0.01413776, 0.01370974, 0.01037035,
       0.01071712, 0.01238072, 0.016361  , 0.01281465, 0.00922191,
       0.01271443, 0.01211584, 0.01037309, 0.01078151, 0.01195847,
       0.01158379, 0.00915844, 0.01400002, 0.01062667, 0.00988708,
       0.01348598, 0.01415621, 0.01089404, 0.01284735, 0.0114948 ,
       0.01265388, 0.01207014, 0.01032   , 0.00996525, 0.01391452,
       0.01237294, 0.01276925, 0.01213285, 0.01440823, 0.01101585,
       0.01231714, 0.01118211, 0.01229298, 0.01276286, 0.01441778,
       0.01295595, 0.01045303, 0.01257633, 0.01303287, 0.01303

In [39]:
spread_vec2 = np.std(vec2,axis = 0) # standard deviation for all features of label 1
spread_vec2

array([0.01229052, 0.01255128, 0.01087892, 0.01233027, 0.01013627,
       0.01001011, 0.00911291, 0.00931317, 0.01064017, 0.00924716,
       0.00893481, 0.01250302, 0.01059081, 0.00988682, 0.01006412,
       0.01166025, 0.00945288, 0.01028752, 0.01088503, 0.00999892,
       0.01013728, 0.00983017, 0.01264086, 0.01244268, 0.01289414,
       0.00858137, 0.00972914, 0.01522133, 0.01101335, 0.01057337,
       0.01125361, 0.01102559, 0.01158066, 0.01277527, 0.01055663,
       0.01102105, 0.01037755, 0.01479097, 0.01060294, 0.0097146 ,
       0.01043513, 0.01230142, 0.0097961 , 0.01116352, 0.01180683,
       0.01144283, 0.01025364, 0.01179124, 0.00929331, 0.01028297,
       0.01232003, 0.01157222, 0.01063137, 0.01160087, 0.01080091,
       0.01032701, 0.01212425, 0.00950868, 0.00966231, 0.01389578,
       0.01120842, 0.01103983, 0.01059729, 0.01233059, 0.011621  ,
       0.01153278, 0.01163337, 0.01175023, 0.01084104, 0.01275301,
       0.01150844, 0.01119668, 0.01032828, 0.0133003 , 0.01041

In [42]:
interclass_distance = np.linalg.norm(mean_vec1 - mean_vec2) #interclass distance between label 0 and label1
interclass_distance

1.0098401916797553