<a href="https://colab.research.google.com/github/thanmai91/thanmai91/blob/main/purchaseA1%2CA2%2CA3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_excel('/content/data.xlsx')
df

Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)  \
0      C_1           20             6                 2           386   
1      C_2           16             3                 6           289   
2      C_3           27             6                 2           393   
3      C_4           19             1                 2           110   
4      C_5           24             4                 2           280   
5      C_6           22             1                 5           167   
6      C_7           15             4                 2           271   
7      C_8           18             4                 2           274   
8      C_9           21             1                 4           148   
9     C_10           16             2                 4           198   

   Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  ...  \
0         NaN         NaN         NaN         NaN         NaN  ...   
1         NaN         NaN         NaN         NaN         NaN  ...   
2         NaN         NaN         NaN         NaN         NaN  ...   
3         NaN         NaN         NaN         NaN         NaN  ...   
4         NaN         NaN         NaN         NaN         NaN  ...   
5         NaN         NaN         NaN         NaN         NaN  ...   
6         NaN         NaN         NaN         NaN         NaN  ...   
7         NaN         NaN         NaN         NaN         NaN  ...   
8         NaN         NaN         NaN         NaN         NaN  ...   
9         NaN         NaN         NaN         NaN         NaN  ...   

   Unnamed: 12  Unnamed: 13  Unnamed: 14  Unnamed: 15  Unnamed: 16  \
0          NaN          NaN          NaN          NaN          NaN   
1          NaN          NaN          NaN          NaN          NaN   
2          NaN          NaN          NaN          NaN          NaN   
3          NaN          NaN          NaN          NaN          NaN   
4          NaN          NaN          NaN          NaN          NaN   
5          NaN          NaN          NaN          NaN          NaN   
6          NaN          NaN          NaN          NaN          NaN   
7          NaN          NaN          NaN          NaN          NaN   
8          NaN          NaN          NaN          NaN          NaN   
9          NaN          NaN          NaN          NaN          NaN   

   Unnamed: 17  Unnamed: 18  Candy  Mango  Milk  
0          NaN          NaN    1.0   55.0  18.0  
1          NaN          NaN    NaN    NaN   NaN  
2          NaN          NaN    NaN    NaN   NaN  
3          NaN          NaN    NaN    NaN   NaN  
4          NaN          NaN    NaN    NaN   NaN  
5          NaN          NaN    NaN    NaN   NaN  
6          NaN          NaN    NaN    NaN   NaN  
7          NaN          NaN    NaN    NaN   NaN  
8          NaN          NaN    NaN    NaN   NaN  
9          NaN          NaN    NaN    NaN   NaN  

[10 rows x 22 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Customer          10 non-null     object 
 1   Candies (#)       10 non-null     int64  
 2   Mangoes (Kg)      10 non-null     int64  
 3   Milk Packets (#)  10 non-null     int64  
 4   Payment (Rs)      10 non-null     int64  
 5   Unnamed: 5        0 non-null      float64
 6   Unnamed: 6        0 non-null      float64
 7   Unnamed: 7        0 non-null      float64
 8   Unnamed: 8        0 non-null      float64
 9   Unnamed: 9        0 non-null      float64
 10  Unnamed: 10       0 non-null      float64
 11  Unnamed: 11       0 non-null      float64
 12  Unnamed: 12       0 non-null      float64
 13  Unnamed: 13       0 non-null      float64
 14  Unnamed: 14       0 non-null      float64
 15  Unnamed: 15       0 non-null      float64
 16  Unnamed: 16       0 non-null      float64
 17  

In [ ]:
df = df.drop(['Unnamed: 5'],axis = 1)


In [ ]:
df.drop(df.iloc[:, 5:18], inplace=True, axis=1)

In [ ]:
df

Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)  Candy  \
0      C_1           20             6                 2           386    1.0   
1      C_2           16             3                 6           289    NaN   
2      C_3           27             6                 2           393    NaN   
3      C_4           19             1                 2           110    NaN   
4      C_5           24             4                 2           280    NaN   
5      C_6           22             1                 5           167    NaN   
6      C_7           15             4                 2           271    NaN   
7      C_8           18             4                 2           274    NaN   
8      C_9           21             1                 4           148    NaN   
9     C_10           16             2                 4           198    NaN   

   Mango  Milk  
0   55.0  18.0  
1    NaN   NaN  
2    NaN   NaN  
3    NaN   NaN  
4    NaN   NaN  
5    NaN   NaN  
6    NaN   NaN  
7    NaN   NaN  
8    NaN   NaN  
9    NaN   NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Customer          10 non-null     object
 1   Candies (#)       10 non-null     int64 
 2   Mangoes (Kg)      10 non-null     int64 
 3   Milk Packets (#)  10 non-null     int64 
 4   Payment (Rs)      10 non-null     int64 
dtypes: int64(4), object(1)
memory usage: 528.0+ bytes


In [ ]:
 df = df.drop(df.iloc[:,5:7],axis = 1)

In [ ]:
df = df.drop(['Milk'], axis =1)

In [ ]:
df

Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)
0      C_1           20             6                 2           386
1      C_2           16             3                 6           289
2      C_3           27             6                 2           393
3      C_4           19             1                 2           110
4      C_5           24             4                 2           280
5      C_6           22             1                 5           167
6      C_7           15             4                 2           271
7      C_8           18             4                 2           274
8      C_9           21             1                 4           148
9     C_10           16             2                 4           198

In [ ]:
a = df.iloc[:,1:4].values
a

array([[20,  6,  2],
       [16,  3,  6],
       [27,  6,  2],
       [19,  1,  2],
       [24,  4,  2],
       [22,  1,  5],
       [15,  4,  2],
       [18,  4,  2],
       [21,  1,  4],
       [16,  2,  4]])

In [ ]:
c = df.iloc[:,4].values
c

array([386, 289, 393, 110, 280, 167, 271, 274, 148, 198])

In [ ]:
a.shape

(10, 3)

In [ ]:
c.shape

(10,)

In [ ]:
dimensionality = a.shape[1]
dimensionality

3

In [ ]:
num_vectors = a.shape[0]
num_vectors

10

In [ ]:
type(c)

numpy.ndarray

In [ ]:
import numpy as np
np.linalg.matrix_rank(a)

3

In [ ]:
b = np.linalg.pinv(a)
b

array([[-0.01008596, -0.03124505,  0.01013951,  0.0290728 ,  0.0182907 ,
         0.01161794, -0.00771348,  0.00095458,  0.01743623, -0.00542016],
       [ 0.09059668,  0.07263726,  0.03172933, -0.09071908, -0.01893196,
        -0.06926996,  0.05675464,  0.03152577, -0.07641966,  0.00357352],
       [ 0.00299878,  0.15874243, -0.05795468, -0.06609024, -0.06295043,
         0.03348017,  0.01541831, -0.01070461,  0.00029003,  0.05938755]])

In [ ]:
x = np.matmul(b,c)
x

array([ 1., 55., 18.])

In [ ]:
clas = [0,0,0,0,0,0,0,0,0,0]
df['Class'] = clas
df

Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)  Class
0      C_1           20             6                 2           386      0
1      C_2           16             3                 6           289      0
2      C_3           27             6                 2           393      0
3      C_4           19             1                 2           110      0
4      C_5           24             4                 2           280      0
5      C_6           22             1                 5           167      0
6      C_7           15             4                 2           271      0
7      C_8           18             4                 2           274      0
8      C_9           21             1                 4           148      0
9     C_10           16             2                 4           198      0

In [ ]:
df.loc[df['Payment (Rs)'] > 200, 'Class'] = 1
df

Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)  Class
0      C_1           20             6                 2           386      1
1      C_2           16             3                 6           289      1
2      C_3           27             6                 2           393      1
3      C_4           19             1                 2           110      0
4      C_5           24             4                 2           280      1
5      C_6           22             1                 5           167      0
6      C_7           15             4                 2           271      1
7      C_8           18             4                 2           274      1
8      C_9           21             1                 4           148      0
9     C_10           16             2                 4           198      0

In [ ]:
x = df.iloc[:,1:5].values
x

array([[ 20,   6,   2, 386],
       [ 16,   3,   6, 289],
       [ 27,   6,   2, 393],
       [ 19,   1,   2, 110],
       [ 24,   4,   2, 280],
       [ 22,   1,   5, 167],
       [ 15,   4,   2, 271],
       [ 18,   4,   2, 274],
       [ 21,   1,   4, 148],
       [ 16,   2,   4, 198]])

In [ ]:
y = df.iloc[:,5].values
y

array([1, 1, 1, 0, 1, 0, 1, 1, 0, 0])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state = 0)


In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [ ]:
model.fit(x_train,y_train)

LogisticRegression()

In [ ]:
y_pred = model.predict(x_test)
y_pred

array([1, 0, 1])

In [ ]:
y_test

array([1, 0, 1])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_pred,y_test)*100

100.0

In [ ]:
model.predict([[25,2,1,390]])

array([1])

In [ ]:
model.predict([[16,1,4,153]])

array([0])